/**
 * Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */
package com.oracle.bmc.generativeaiinference.model;

/**
 * Represents a single instance of assistant message.
 *
 * <p>Note: When responding to a tool call, set {@code content} to {@code null} (not {@code ""}).
 * This ensures the model correctly processes tool call messages in multi-step interactions. <br>
 * Note: Objects should always be created or deserialized using the {@link Builder}. This model
 * distinguishes fields that are {@code null} because they are unset from fields that are explicitly
 * set to {@code null}. This is done in the setter methods of the {@link Builder}, which maintain a
 * set of all explicitly set fields called {@link Builder#__explicitlySet__}. The {@link
 * #hashCode()} and {@link #equals(Object)} methods are implemented to take the explicitly set
 * fields into account. The constructor, on the other hand, does not take the explicitly set fields
 * into account (since the constructor cannot distinguish explicit {@code null} from unset {@code
 * null}).
 */
@jakarta.annotation.Generated(value = "OracleSDKGenerator", comments = "API Version: 20231130")
@com.fasterxml.jackson.databind.annotation.JsonDeserialize(builder = AssistantMessage.Builder.class)
@com.fasterxml.jackson.annotation.JsonTypeInfo(
        use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME,
        include = com.fasterxml.jackson.annotation.JsonTypeInfo.As.PROPERTY,
        property = "role")
@com.fasterxml.jackson.annotation.JsonFilter(
        com.oracle.bmc.http.client.internal.ExplicitlySetBmcModel.EXPLICITLY_SET_FILTER_NAME)
public final class AssistantMessage extends Message {
    @com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
    public static class Builder {
        @com.fasterxml.jackson.annotation.JsonProperty("content")
        private java.util.List<ChatContent> content;

        public Builder content(java.util.List<ChatContent> content) {
            this.content = content;
            this.__explicitlySet__.add("content");
            return this;
        }
        /**
         * An optional name for the participant. Provides the model information to differentiate
         * between participants of the same role.
         */
        @com.fasterxml.jackson.annotation.JsonProperty("name")
        private String name;

        /**
         * An optional name for the participant. Provides the model information to differentiate
         * between participants of the same role.
         *
         * @param name the value to set
         * @return this builder
         */
        public Builder name(String name) {
            this.name = name;
            this.__explicitlySet__.add("name");
            return this;
        }
        /** The refusal message by the assistant. */
        @com.fasterxml.jackson.annotation.JsonProperty("refusal")
        private String refusal;

        /**
         * The refusal message by the assistant.
         *
         * @param refusal the value to set
         * @return this builder
         */
        public Builder refusal(String refusal) {
            this.refusal = refusal;
            this.__explicitlySet__.add("refusal");
            return this;
        }
        /** The tool calls generated by the model, such as function calls. */
        @com.fasterxml.jackson.annotation.JsonProperty("toolCalls")
        private java.util.List<ToolCall> toolCalls;

        /**
         * The tool calls generated by the model, such as function calls.
         *
         * @param toolCalls the value to set
         * @return this builder
         */
        public Builder toolCalls(java.util.List<ToolCall> toolCalls) {
            this.toolCalls = toolCalls;
            this.__explicitlySet__.add("toolCalls");
            return this;
        }
        /**
         * List of annotations generated by the model, including inline citations from web search
         * results.
         */
        @com.fasterxml.jackson.annotation.JsonProperty("annotations")
        private java.util.List<Annotation> annotations;

        /**
         * List of annotations generated by the model, including inline citations from web search
         * results.
         *
         * @param annotations the value to set
         * @return this builder
         */
        public Builder annotations(java.util.List<Annotation> annotations) {
            this.annotations = annotations;
            this.__explicitlySet__.add("annotations");
            return this;
        }
        /** Internal reasoning trace generated during response computation. */
        @com.fasterxml.jackson.annotation.JsonProperty("reasoningContent")
        private String reasoningContent;

        /**
         * Internal reasoning trace generated during response computation.
         *
         * @param reasoningContent the value to set
         * @return this builder
         */
        public Builder reasoningContent(String reasoningContent) {
            this.reasoningContent = reasoningContent;
            this.__explicitlySet__.add("reasoningContent");
            return this;
        }

        @com.fasterxml.jackson.annotation.JsonIgnore
        private final java.util.Set<String> __explicitlySet__ = new java.util.HashSet<String>();

        public AssistantMessage build() {
            AssistantMessage model =
                    new AssistantMessage(
                            this.content,
                            this.name,
                            this.refusal,
                            this.toolCalls,
                            this.annotations,
                            this.reasoningContent);
            for (String explicitlySetProperty : this.__explicitlySet__) {
                model.markPropertyAsExplicitlySet(explicitlySetProperty);
            }
            return model;
        }

        @com.fasterxml.jackson.annotation.JsonIgnore
        public Builder copy(AssistantMessage model) {
            if (model.wasPropertyExplicitlySet("content")) {
                this.content(model.getContent());
            }
            if (model.wasPropertyExplicitlySet("name")) {
                this.name(model.getName());
            }
            if (model.wasPropertyExplicitlySet("refusal")) {
                this.refusal(model.getRefusal());
            }
            if (model.wasPropertyExplicitlySet("toolCalls")) {
                this.toolCalls(model.getToolCalls());
            }
            if (model.wasPropertyExplicitlySet("annotations")) {
                this.annotations(model.getAnnotations());
            }
            if (model.wasPropertyExplicitlySet("reasoningContent")) {
                this.reasoningContent(model.getReasoningContent());
            }
            return this;
        }
    }

    /** Create a new builder. */
    public static Builder builder() {
        return new Builder();
    }

    public Builder toBuilder() {
        return new Builder().copy(this);
    }

    @Deprecated
    public AssistantMessage(
            java.util.List<ChatContent> content,
            String name,
            String refusal,
            java.util.List<ToolCall> toolCalls,
            java.util.List<Annotation> annotations,
            String reasoningContent) {
        super(content);
        this.name = name;
        this.refusal = refusal;
        this.toolCalls = toolCalls;
        this.annotations = annotations;
        this.reasoningContent = reasoningContent;
    }

    /**
     * An optional name for the participant. Provides the model information to differentiate between
     * participants of the same role.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("name")
    private final String name;

    /**
     * An optional name for the participant. Provides the model information to differentiate between
     * participants of the same role.
     *
     * @return the value
     */
    public String getName() {
        return name;
    }

    /** The refusal message by the assistant. */
    @com.fasterxml.jackson.annotation.JsonProperty("refusal")
    private final String refusal;

    /**
     * The refusal message by the assistant.
     *
     * @return the value
     */
    public String getRefusal() {
        return refusal;
    }

    /** The tool calls generated by the model, such as function calls. */
    @com.fasterxml.jackson.annotation.JsonProperty("toolCalls")
    private final java.util.List<ToolCall> toolCalls;

    /**
     * The tool calls generated by the model, such as function calls.
     *
     * @return the value
     */
    public java.util.List<ToolCall> getToolCalls() {
        return toolCalls;
    }

    /**
     * List of annotations generated by the model, including inline citations from web search
     * results.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("annotations")
    private final java.util.List<Annotation> annotations;

    /**
     * List of annotations generated by the model, including inline citations from web search
     * results.
     *
     * @return the value
     */
    public java.util.List<Annotation> getAnnotations() {
        return annotations;
    }

    /** Internal reasoning trace generated during response computation. */
    @com.fasterxml.jackson.annotation.JsonProperty("reasoningContent")
    private final String reasoningContent;

    /**
     * Internal reasoning trace generated during response computation.
     *
     * @return the value
     */
    public String getReasoningContent() {
        return reasoningContent;
    }

    @Override
    public String toString() {
        return this.toString(true);
    }

    /**
     * Return a string representation of the object.
     *
     * @param includeByteArrayContents true to include the full contents of byte arrays
     * @return string representation
     */
    public String toString(boolean includeByteArrayContents) {
        java.lang.StringBuilder sb = new java.lang.StringBuilder();
        sb.append("AssistantMessage(");
        sb.append("super=").append(super.toString(includeByteArrayContents));
        sb.append(", name=").append(String.valueOf(this.name));
        sb.append(", refusal=").append(String.valueOf(this.refusal));
        sb.append(", toolCalls=").append(String.valueOf(this.toolCalls));
        sb.append(", annotations=").append(String.valueOf(this.annotations));
        sb.append(", reasoningContent=").append(String.valueOf(this.reasoningContent));
        sb.append(")");
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof AssistantMessage)) {
            return false;
        }

        AssistantMessage other = (AssistantMessage) o;
        return java.util.Objects.equals(this.name, other.name)
                && java.util.Objects.equals(this.refusal, other.refusal)
                && java.util.Objects.equals(this.toolCalls, other.toolCalls)
                && java.util.Objects.equals(this.annotations, other.annotations)
                && java.util.Objects.equals(this.reasoningContent, other.reasoningContent)
                && super.equals(other);
    }

    @Override
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        result = (result * PRIME) + (this.name == null ? 43 : this.name.hashCode());
        result = (result * PRIME) + (this.refusal == null ? 43 : this.refusal.hashCode());
        result = (result * PRIME) + (this.toolCalls == null ? 43 : this.toolCalls.hashCode());
        result = (result * PRIME) + (this.annotations == null ? 43 : this.annotations.hashCode());
        result =
                (result * PRIME)
                        + (this.reasoningContent == null ? 43 : this.reasoningContent.hashCode());
        return result;
    }
}
