/**
 * Copyright (c) 2016, 2023, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */
package com.oracle.bmc.certificatesmanagement.requests;

import com.oracle.bmc.certificatesmanagement.model.*;
/**
 * <b>Example: </b>Click <a
 * href="https://docs.cloud.oracle.com/en-us/iaas/tools/java-sdk-examples/latest/certificatesmanagement/ScheduleCertificateAuthorityVersionDeletionExample.java.html"
 * target="_blank" rel="noopener noreferrer">here</a> to see how to use
 * ScheduleCertificateAuthorityVersionDeletionRequest.
 */
@jakarta.annotation.Generated(value = "OracleSDKGenerator", comments = "API Version: 20210224")
public class ScheduleCertificateAuthorityVersionDeletionRequest
        extends com.oracle.bmc.requests.BmcRequest<
                com.oracle.bmc.certificatesmanagement.model
                        .ScheduleCertificateAuthorityVersionDeletionDetails> {

    /** The OCID of the certificate authority (CA). */
    private String certificateAuthorityId;

    /** The OCID of the certificate authority (CA). */
    public String getCertificateAuthorityId() {
        return certificateAuthorityId;
    }
    /** The version number of the certificate authority (CA). */
    private Long certificateAuthorityVersionNumber;

    /** The version number of the certificate authority (CA). */
    public Long getCertificateAuthorityVersionNumber() {
        return certificateAuthorityVersionNumber;
    }
    /** The details of the request to delete a CA version. */
    private com.oracle.bmc.certificatesmanagement.model
                    .ScheduleCertificateAuthorityVersionDeletionDetails
            scheduleCertificateAuthorityVersionDeletionDetails;

    /** The details of the request to delete a CA version. */
    public com.oracle.bmc.certificatesmanagement.model
                    .ScheduleCertificateAuthorityVersionDeletionDetails
            getScheduleCertificateAuthorityVersionDeletionDetails() {
        return scheduleCertificateAuthorityVersionDeletionDetails;
    }
    /**
     * Unique Oracle-assigned identifier for the request. If provided, the returned request ID will
     * include this value. Otherwise, a random request ID will be generated by the service.
     */
    private String opcRequestId;

    /**
     * Unique Oracle-assigned identifier for the request. If provided, the returned request ID will
     * include this value. Otherwise, a random request ID will be generated by the service.
     */
    public String getOpcRequestId() {
        return opcRequestId;
    }
    /**
     * For optimistic concurrency control. In the PUT or DELETE call for a resource, set the {@code
     * if-match} parameter to the value of the etag from a previous GET or POST response for that
     * resource. The resource will be updated or deleted only if the etag you provide matches the
     * resource's current etag value.
     */
    private String ifMatch;

    /**
     * For optimistic concurrency control. In the PUT or DELETE call for a resource, set the {@code
     * if-match} parameter to the value of the etag from a previous GET or POST response for that
     * resource. The resource will be updated or deleted only if the etag you provide matches the
     * resource's current etag value.
     */
    public String getIfMatch() {
        return ifMatch;
    }

    /**
     * Alternative accessor for the body parameter.
     *
     * @return body parameter
     */
    @Override
    @com.oracle.bmc.InternalSdk
    public com.oracle.bmc.certificatesmanagement.model
                    .ScheduleCertificateAuthorityVersionDeletionDetails
            getBody$() {
        return scheduleCertificateAuthorityVersionDeletionDetails;
    }

    public static class Builder
            implements com.oracle.bmc.requests.BmcRequest.Builder<
                    ScheduleCertificateAuthorityVersionDeletionRequest,
                    com.oracle.bmc.certificatesmanagement.model
                            .ScheduleCertificateAuthorityVersionDeletionDetails> {
        private com.oracle.bmc.http.client.RequestInterceptor invocationCallback = null;
        private com.oracle.bmc.retrier.RetryConfiguration retryConfiguration = null;

        /** The OCID of the certificate authority (CA). */
        private String certificateAuthorityId = null;

        /**
         * The OCID of the certificate authority (CA).
         *
         * @param certificateAuthorityId the value to set
         * @return this builder instance
         */
        public Builder certificateAuthorityId(String certificateAuthorityId) {
            this.certificateAuthorityId = certificateAuthorityId;
            return this;
        }

        /** The version number of the certificate authority (CA). */
        private Long certificateAuthorityVersionNumber = null;

        /**
         * The version number of the certificate authority (CA).
         *
         * @param certificateAuthorityVersionNumber the value to set
         * @return this builder instance
         */
        public Builder certificateAuthorityVersionNumber(Long certificateAuthorityVersionNumber) {
            this.certificateAuthorityVersionNumber = certificateAuthorityVersionNumber;
            return this;
        }

        /** The details of the request to delete a CA version. */
        private com.oracle.bmc.certificatesmanagement.model
                        .ScheduleCertificateAuthorityVersionDeletionDetails
                scheduleCertificateAuthorityVersionDeletionDetails = null;

        /**
         * The details of the request to delete a CA version.
         *
         * @param scheduleCertificateAuthorityVersionDeletionDetails the value to set
         * @return this builder instance
         */
        public Builder scheduleCertificateAuthorityVersionDeletionDetails(
                com.oracle.bmc.certificatesmanagement.model
                                .ScheduleCertificateAuthorityVersionDeletionDetails
                        scheduleCertificateAuthorityVersionDeletionDetails) {
            this.scheduleCertificateAuthorityVersionDeletionDetails =
                    scheduleCertificateAuthorityVersionDeletionDetails;
            return this;
        }

        /**
         * Unique Oracle-assigned identifier for the request. If provided, the returned request ID
         * will include this value. Otherwise, a random request ID will be generated by the service.
         */
        private String opcRequestId = null;

        /**
         * Unique Oracle-assigned identifier for the request. If provided, the returned request ID
         * will include this value. Otherwise, a random request ID will be generated by the service.
         *
         * @param opcRequestId the value to set
         * @return this builder instance
         */
        public Builder opcRequestId(String opcRequestId) {
            this.opcRequestId = opcRequestId;
            return this;
        }

        /**
         * For optimistic concurrency control. In the PUT or DELETE call for a resource, set the
         * {@code if-match} parameter to the value of the etag from a previous GET or POST response
         * for that resource. The resource will be updated or deleted only if the etag you provide
         * matches the resource's current etag value.
         */
        private String ifMatch = null;

        /**
         * For optimistic concurrency control. In the PUT or DELETE call for a resource, set the
         * {@code if-match} parameter to the value of the etag from a previous GET or POST response
         * for that resource. The resource will be updated or deleted only if the etag you provide
         * matches the resource's current etag value.
         *
         * @param ifMatch the value to set
         * @return this builder instance
         */
        public Builder ifMatch(String ifMatch) {
            this.ifMatch = ifMatch;
            return this;
        }

        /**
         * Set the invocation callback for the request to be built.
         *
         * @param invocationCallback the invocation callback to be set for the request
         * @return this builder instance
         */
        public Builder invocationCallback(
                com.oracle.bmc.http.client.RequestInterceptor invocationCallback) {
            this.invocationCallback = invocationCallback;
            return this;
        }

        /**
         * Set the retry configuration for the request to be built.
         *
         * @param retryConfiguration the retry configuration to be used for the request
         * @return this builder instance
         */
        public Builder retryConfiguration(
                com.oracle.bmc.retrier.RetryConfiguration retryConfiguration) {
            this.retryConfiguration = retryConfiguration;
            return this;
        }

        /**
         * Copy method to populate the builder with values from the given instance.
         *
         * @return this builder instance
         */
        public Builder copy(ScheduleCertificateAuthorityVersionDeletionRequest o) {
            certificateAuthorityId(o.getCertificateAuthorityId());
            certificateAuthorityVersionNumber(o.getCertificateAuthorityVersionNumber());
            scheduleCertificateAuthorityVersionDeletionDetails(
                    o.getScheduleCertificateAuthorityVersionDeletionDetails());
            opcRequestId(o.getOpcRequestId());
            ifMatch(o.getIfMatch());
            invocationCallback(o.getInvocationCallback());
            retryConfiguration(o.getRetryConfiguration());
            return this;
        }

        /**
         * Build the instance of ScheduleCertificateAuthorityVersionDeletionRequest as configured by
         * this builder
         *
         * <p>Note that this method takes calls to {@link
         * Builder#invocationCallback(com.oracle.bmc.http.client.RequestInterceptor)} into account,
         * while the method {@link Builder#buildWithoutInvocationCallback} does not.
         *
         * <p>This is the preferred method to build an instance.
         *
         * @return instance of ScheduleCertificateAuthorityVersionDeletionRequest
         */
        public ScheduleCertificateAuthorityVersionDeletionRequest build() {
            ScheduleCertificateAuthorityVersionDeletionRequest request =
                    buildWithoutInvocationCallback();
            request.setInvocationCallback(invocationCallback);
            request.setRetryConfiguration(retryConfiguration);
            return request;
        }

        /**
         * Alternative setter for the body parameter.
         *
         * @param body the body parameter
         * @return this builder instance
         */
        @com.oracle.bmc.InternalSdk
        public Builder body$(
                com.oracle.bmc.certificatesmanagement.model
                                .ScheduleCertificateAuthorityVersionDeletionDetails
                        body) {
            scheduleCertificateAuthorityVersionDeletionDetails(body);
            return this;
        }

        /**
         * Build the instance of ScheduleCertificateAuthorityVersionDeletionRequest as configured by
         * this builder
         *
         * <p>Note that this method does not take calls to {@link
         * Builder#invocationCallback(com.oracle.bmc.http.client.RequestInterceptor)} into account,
         * while the method {@link Builder#build} does
         *
         * @return instance of ScheduleCertificateAuthorityVersionDeletionRequest
         */
        public ScheduleCertificateAuthorityVersionDeletionRequest buildWithoutInvocationCallback() {
            ScheduleCertificateAuthorityVersionDeletionRequest request =
                    new ScheduleCertificateAuthorityVersionDeletionRequest();
            request.certificateAuthorityId = certificateAuthorityId;
            request.certificateAuthorityVersionNumber = certificateAuthorityVersionNumber;
            request.scheduleCertificateAuthorityVersionDeletionDetails =
                    scheduleCertificateAuthorityVersionDeletionDetails;
            request.opcRequestId = opcRequestId;
            request.ifMatch = ifMatch;
            return request;
            // new ScheduleCertificateAuthorityVersionDeletionRequest(certificateAuthorityId,
            // certificateAuthorityVersionNumber,
            // scheduleCertificateAuthorityVersionDeletionDetails, opcRequestId, ifMatch);
        }
    }

    /**
     * Return an instance of {@link Builder} that allows you to modify request properties.
     *
     * @return instance of {@link Builder} that allows you to modify request properties.
     */
    public Builder toBuilder() {
        return new Builder()
                .certificateAuthorityId(certificateAuthorityId)
                .certificateAuthorityVersionNumber(certificateAuthorityVersionNumber)
                .scheduleCertificateAuthorityVersionDeletionDetails(
                        scheduleCertificateAuthorityVersionDeletionDetails)
                .opcRequestId(opcRequestId)
                .ifMatch(ifMatch);
    }

    /**
     * Return a new builder for this request object.
     *
     * @return builder for the request object
     */
    public static Builder builder() {
        return new Builder();
    }

    @Override
    public String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder();
        sb.append("(");
        sb.append("super=").append(super.toString());
        sb.append(",certificateAuthorityId=").append(String.valueOf(this.certificateAuthorityId));
        sb.append(",certificateAuthorityVersionNumber=")
                .append(String.valueOf(this.certificateAuthorityVersionNumber));
        sb.append(",scheduleCertificateAuthorityVersionDeletionDetails=")
                .append(String.valueOf(this.scheduleCertificateAuthorityVersionDeletionDetails));
        sb.append(",opcRequestId=").append(String.valueOf(this.opcRequestId));
        sb.append(",ifMatch=").append(String.valueOf(this.ifMatch));
        sb.append(")");
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof ScheduleCertificateAuthorityVersionDeletionRequest)) {
            return false;
        }

        ScheduleCertificateAuthorityVersionDeletionRequest other =
                (ScheduleCertificateAuthorityVersionDeletionRequest) o;
        return super.equals(o)
                && java.util.Objects.equals(
                        this.certificateAuthorityId, other.certificateAuthorityId)
                && java.util.Objects.equals(
                        this.certificateAuthorityVersionNumber,
                        other.certificateAuthorityVersionNumber)
                && java.util.Objects.equals(
                        this.scheduleCertificateAuthorityVersionDeletionDetails,
                        other.scheduleCertificateAuthorityVersionDeletionDetails)
                && java.util.Objects.equals(this.opcRequestId, other.opcRequestId)
                && java.util.Objects.equals(this.ifMatch, other.ifMatch);
    }

    @Override
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        result =
                (result * PRIME)
                        + (this.certificateAuthorityId == null
                                ? 43
                                : this.certificateAuthorityId.hashCode());
        result =
                (result * PRIME)
                        + (this.certificateAuthorityVersionNumber == null
                                ? 43
                                : this.certificateAuthorityVersionNumber.hashCode());
        result =
                (result * PRIME)
                        + (this.scheduleCertificateAuthorityVersionDeletionDetails == null
                                ? 43
                                : this.scheduleCertificateAuthorityVersionDeletionDetails
                                        .hashCode());
        result = (result * PRIME) + (this.opcRequestId == null ? 43 : this.opcRequestId.hashCode());
        result = (result * PRIME) + (this.ifMatch == null ? 43 : this.ifMatch.hashCode());
        return result;
    }
}
